from tkinter import*
window=Tk()
window.title("getting started with widgets")
window.geometry("400x400")
lbl=Label(text = "this will calculate the product of a number",fg="white",bg="black",height=2,width=400)
n1lbl=Label(text = "enter the number",bg="black",)
n1entry= Entry()
n2lbl=Label(text = "enter the second number",bg="black")
n2entry=Entry()
def multiply():
    n1=int(n1entry.get())
    n2=int(n2entry.get())
    product=n1*n2
textbox.insert(END,("her is the answer")) 
textbox.insert(END,("her is the ",product)) 
btn=Button(text="calculate",command=multiply,bg="black",height="20")
lbl.pack()
n1lbl.pack()
n2lbl.pack()
n1entry.pack()
n2entry.pack()
btn.pack()
text_box.pack()
testing.pack()